---
- name: Create local certs dir
  file:
    path: "{{ temp_cert_dir }}"
    state: directory
  become: false
  delegate_to: localhost

- name: Create master cert conf
  template:
    src: server_ssl_conf.j2
    dest: "{{ temp_cert_dir }}/{{ ansible_hostname }}.conf"
  delegate_to: localhost
  become: false

- name: Create node cert conf
  template:
    src: node_ssl_conf.j2
    dest: "{{ temp_cert_dir }}/{{ item }}.conf"
  with_items:
     - "{{ groups.minions }}"
  delegate_to: localhost
  become: false

- name: Generate CA key
  command: openssl genrsa -out ca.key 2048
  args:
    chdir: "{{ temp_cert_dir }}"
  delegate_to: localhost
  become: false

- name: Generate CA cert
  command: openssl req -x509 -new -nodes -key ca.key -subj "/CN={{ item }}" -days 10000 -out ca.crt -config {{ item }}.conf
  args:
   chdir: "{{ temp_cert_dir }}"
  with_items:
    - "{{ groups.master }}"
  delegate_to: localhost

- name: Generate Master/Node key
  command: openssl genrsa -out {{ item }}.key 2048
  args:
    chdir: "{{ temp_cert_dir }}"
  with_items:
    - "{{ groups.master }}"
    - "{{ groups.minions }}"
  delegate_to: localhost
  become: false

- name: Generate Master/Node csr
  command: openssl req -new -key {{ item }}.key -subj "/CN={{ item }}" -out {{ item }}.csr
  args:
    chdir: "{{ temp_cert_dir }}"
  with_items:
    - "{{ groups.master }}"
    - "{{ groups.minions }}"
  delegate_to: localhost
  become: false

- name: Generate master/node cert
  command: openssl x509 -req -in {{ item }}.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out {{ item }}.crt -days 10000 -extensions v3_req -extfile {{ item }}.conf
  args:
    chdir: "{{ temp_cert_dir }}"
  with_items:
    - "{{ groups.master }}"
    - "{{ groups.minions }}"
  delegate_to: localhost
  become: false

- name: Copy certs from localhost to master
  synchronize:
    src: "{{ temp_cert_dir }}"
    dest: /etc/kubernetes/certs/


